In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
IrisData = pd.read_csv('iris.data', header=None)
IrisData.columns = ['Sepal Length','Sepal Width','Petal Length','Petal Width','Type']

In [3]:
listname = []
for i in range(len(IrisData['Type'])):
    if not(IrisData['Type'][i] in listname):
        listname.append(IrisData['Type'][i])

In [4]:
dicttypes = dict(zip(listname,[0,1,2]))
dicttypes

{'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}

In [5]:
categoria = []
for i in IrisData['Type']:
    categoria.append(dicttypes[i])

In [6]:
IrisData['Cate-type'] = categoria
IrisData

Sepal Length  Sepal Width  Petal Length  Petal Width            Type  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

     Cate-type  
0            0  
1            0  
2            0  
3            0  
4            0  
..         ...  
145          2  
146          2  
147          2  
148          2  
149          2  

[150 rows x 6 columns]

In [7]:
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split

In [8]:
x = IrisData[['Petal Length', 'Petal Width']]
y = IrisData['Cate-type']

In [9]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y , test_size=0.3)

In [10]:
Model_kmeans = KMeans(n_clusters=3)
Mcluester  = Model_kmeans.fit(x_treino)

In [11]:
Mcluester.inertia_

24.878532282282286

In [12]:
Mcluester.labels_

array([1, 0, 0, 1, 1, 2, 1, 0, 2, 1, 2, 0, 0, 2, 2, 0, 1, 1, 1, 0, 2, 2,
       1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 1, 2, 0, 1, 2, 2, 1, 0, 2, 0, 2,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 1,
       2, 1, 2, 1, 0, 2, 2, 2, 2, 1, 2, 1, 2, 1, 0, 1, 0, 0, 1, 2, 1, 1,
       0, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 1, 2, 2, 0, 0, 1])

In [13]:
Mcluester.cluster_centers_

array([[1.46875   , 0.25      ],
       [5.58055556, 1.98888889],
       [4.2027027 , 1.32432432]])

In [30]:
centerx = []
centery = []
for i in range(3):
    centerx.append(Mcluester.cluster_centers_[i][0])
    centery.append(Mcluester.cluster_centers_[i][1])

print(centerx)
print(centery)

[1.46875, 5.580555555555556, 4.202702702702703]
[0.24999999999999956, 1.9888888888888887, 1.3243243243243243]


In [15]:
colores = {2:"Blue",0:"Orange",1:"green" }
color_names  = {'Iris-virginica':"Blue",'Iris-setosa':"Orange",'Iris-versicolor':"green" }
Array_Colors =[colores[x] for x in IrisData['Cate-type']]

In [17]:
result = pd.DataFrame(y_treino)
result['Previsto'] = Mcluester.labels_

In [18]:
Mcluester.cluster_centers_

array([[1.46875   , 0.25      ],
       [5.58055556, 1.98888889],
       [4.2027027 , 1.32432432]])

In [19]:
color_names

{'Iris-virginica': 'Blue', 'Iris-setosa': 'Orange', 'Iris-versicolor': 'green'}

In [20]:
colores

{2: 'Blue', 0: 'Orange', 1: 'green'}

In [21]:
troca = []
for i in result['Previsto']:
    if i == 0:
        troca.append(2)
    if i == 2:
        troca.append(0)
    if i == 1:
        troca.append(1)

In [22]:
result['Previsto'] = troca

In [46]:
import plotly.express as px

In [75]:
fig = px.scatter(IrisData,x='Petal Length',y='Petal Width', color='Type')
fig.add_scatter(x=centerx,y=centery, mode="markers", name='Centroide',marker=dict(size=8, color="Black"))
fig.show()